export const ADMIN_PATH = '/tara-system';

export const ROLES = {
  DEVELOPER: 'DEVELOPER',
  ADMINISTRATOR: 'ADMINISTRATOR',
  KEUANGAN: 'KEUANGAN',
  KARANG_TARUNA: 'KARANG TARUNA',
  KETUA_RT: 'KETUA RT',
  WARGA: 'WARGA',
};

export const ADMIN_ROLES = [
  ROLES.DEVELOPER,
  ROLES.ADMINISTRATOR,
  ROLES.KEUANGAN,
  ROLES.KARANG_TARUNA,
  ROLES.KETUA_RT,
];
